site_name: Proyecto-Intermodular
site_description: Documentación del proyecto PI de ASIR
site_author: AlejandroMarinyo
site_url: https://AlejandroMarinyo.github.io/Proyecto-Intermodular/

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro

nav:
  - Inicio: index.md
  - Introducción: Introduccion.md
  - Marco Tecnológico: Marco_Tecnologico.md
  - Diseño y Planificación: Diseno_y_Planificacion.md
  - Desarrollo: Desarrollo.md
  - Resultados: Resultados.md
  - Conclusiones y mejoras futuras: Conclusiones.md
  - Bibliografía : Bibliografia.md
  - Anexos: Anexos.md

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
